spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudlearn?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update   # 第一次建表用create,之后用update，
    show-sql: true    # 在控制台打印出sql语句
  application:
    name: microservice-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExecutor: TRACE

---
spring:
  profiles: type1
server:
  port: 8000
---
spring:
  profiles: type2
server:
  port: 8001