server:
  port: 8010
spring:
  application:
    name: microservie-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
user:
  userServiceUrl: http://peer1:8761/eureka/,http://peer2:8762/eureka/